packages:
  - 'packages/*'

allowBuilds:
  esbuild: set this to true or false

autoInstallPeers: false

peerDependencyRules:
  allowAny:
    - '@deepseek-ai/*'
    - '@cryptocurpays/*'
  ignoreMissing:
    - '@deepseek-ai/*'
